import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :gesttalt, GesttaltWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :gesttalt, GesttaltWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

config :gesttalt, :logger, [
  {:handler, :gesttalt_opentelemetry, OtelMetricExporter.LogHandler,
   %{
     config: %{
       metadata: [:application, :domain, :line, :mfa, :pid],
       metadata_map: %{request_id: "http.request.id"}
     }
   }}
]

config :opentelemetry,
  span_processor: :batch

config :opentelemetry_exporter,
  otlp_protocol: :http_protobuf,
  otlp_compression: :gzip

config :otel_metric_exporter,
  otlp_protocol: :http_protobuf,
  otlp_compression: :gzip

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
