apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gesttalt.fullname" . }}-media
  labels:
    {{- include "gesttalt.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.media.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.media.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gesttalt.fullname" . }}-caddy
  labels:
    {{- include "gesttalt.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.caddy.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.caddy.persistence.size }}
