apiVersion: v1
kind: Service
metadata:
  name: {{ include "gesttalt.fullname" . }}-web
  labels:
    {{- include "gesttalt.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gesttalt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: phoenix
      port: 4000
      targetPort: phoenix
